trigger:
- dev

resources:
- repo: self

variables:
  tag: 'shoefury'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: selfhost
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
  - job: Push
    displayName: Push to docker hub
    steps:
      
