trigger:
- dev

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: selfhost
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: 'build'
        repository: 'maciejwojtkowiak/shoefury-backend'
        Dockerfile: '**/Dockerfile'
        tags: 'latest'
  - job: Push
    displayName: Push to repository
    pool:
        name: selfhost
    steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'docker-hub'
          command: 'login'
      - task: Docker@2
        inputs:
          repository: 'maciejwojtkowiak/shoefury-backend'
          command: 'push'
          tags: 'latest'
          

      
